### PR TITLE
Install correctly with setup.py

### PR DESCRIPTION
**Pull request by hroncok**
This change makes the package correctly installable on Linux without any hacks and Bash scripts.

I also removed all the shebangs in extra commit, because shebang is only needed in the launch script.

I made it so that all the data files are installed in `/usr/share/horus`.

Important notes:
- I haven't test the `package.sh` script scenario
- I haven't touched Mac OS X specal setup file

### CODE REVIEW

**Comment by hroncok** [comment]
I guess exactly here on [this line](https://github.com/bq/horus/blob/develop/setup_mac.py#L8) the Mac OS X setup.py will fail. I'll change it to the new location

**Comment by Jesus89** [comment]
I need to make it compatible with older deb, exe and dmg distributions, and then merge it.
Thanks!

**Comment by Jesus89** [comment]
Done.

**Comment by hroncok** [comment]
Awesome, thanks.

**Pull request merged**
