### PR TITLE
All the Modal dialogs should call EndModal before destroy

### PR DESCRIPTION
**Pull request by jorgerobles**
Please pick only https://github.com/bq/horus/commit/344f0d391214d67c7c34c09aab9f81ff4f4f7938

### CODE REVIEW

**Comment by Jesus89** [comment]
Great contribution! :D

As soon as I have the Mac I will test it.

By now, can you add 'darwin' distinction in Camera class, in order to use cv2 on Linux and Windows?

Thanks!!

**Comment by jorgerobles** [comment]
Done! Please patch with https://github.com/jorgerobles/horus/commit/df0da550f299869d9abb04652302380f0efec161

**Comment by Jesus89** [comment]
Thanks. We will test it as soon as possible.

**Comment by Jesus89** [comment]
Hi! Try updating this pull request with current 0.1.1 changes into "mac" branch.
Thanks!

**Pull request closed without merging**
